apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: glooedge-e
  namespace: gloo-system
spec:
  releaseName: glooe
  chart:
    spec:
      chart: gloo-ee
      sourceRef:
        kind: HelmRepository
        name: glooedge-e
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 5 
  values:
    license_key: "eyJleHAiOjE2ODM1OTM2ODIsImlhdCI6MTYzMTc1MzY4MiwiayI6IkNLRnI4USIsImx0IjoiZW50IiwicHJvZHVjdCI6Imdsb28ifQ.hqxC313LMDyAMYEMFbgYQlSlpMwMAVR_YBLcFTfHKA4"
